[supervisord]
nodaemon=true
user=root

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
user=root
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_maxbytes=0
stderr_maxbytes=0

[program:messenger-consume]
command=php /var/www/bin/console messenger:consume rabbitmq_notifications --time-limit=3600 --memory-limit=128M
directory=/var/www
autostart=true
autorestart=true
user=root
numprocs=1
stdout_logfile=/var/log/supervisor/messenger.log
stderr_logfile=/var/log/supervisor/messenger.log
startretries=10
startsecs=30

[program:email-consume]
command=php /var/www/bin/console messenger:consume async --time-limit=3600 --memory-limit=128M
directory=/var/www
autostart=true
autorestart=true
user=root
numprocs=1
stdout_logfile=/var/log/supervisor/email.log
stderr_logfile=/var/log/supervisor/email.log
startretries=10
startsecs=30